---
sidebar: sidebar 
permalink: concept_faq.html 
keywords: FAQ, Frequently asked questions, performance, troubleshooting 
summary:  
---
= 性能故障排除


[role="lead"]
本常见问题解答解答解答了有关 Cloud Insights 性能故障排除的常见问题。



== 如何创建环境中所有耗用资源的列表？

Cloud Insights 的关联分析有助于识别 " 指定 " 服务路径中的资源耗用和降级情况。在查看每个对象时，系统会实时执行关联功能生成的分析。通过提供的分析，可以大大减少对性能问题进行故障排除和识别根发生原因所需的时间。要发现资源耗用或已降级，首先需要了解所定义的性能策略生成的违规情况。Cloud Insights 的异常检测功能也可用作一种更主动的方法，用于在应用程序基础架构资源耗竭或降级后，避免其造成服务中断。使用最新查询功能的小工具和信息板均有助于筛选，排序和可视化 IOPS （ Greedy ），利用率或延迟高于预期的资源。



== Cloud Insights 能否提供一个位置来诊断性能问题？

是的。Cloud Insights 中的性能故障排除方法有多种。Cloud Insights 可以采用多种警报方法。通常使用 SNMP ，系统日志和电子邮件警报。通过电子邮件发送的警报，用户可以快速单击并启动到 Cloud Insights 中受影响的资源。管理员可以通过全局搜索窗口键入资源名称来开始分析情况。

Cloud Insights 的违规信息板允许用户根据事件数量，持续时间和一天中的时间确定工作的优先级。各种警报类型的示例包括延迟， IOPS ，利用率，严重性，业务单位甚至应用程序。

Cloud Insights 的关联分析可帮助管理员将对象与受影响的资源进行比较，并确定其对 IOPS ，延迟，利用率， CPU 和 BB 信用的影响。

Cloud Insights 在异常检测和以太网监控方面的最新进步提供了一种更积极主动的方法，可以在资源行为发生服务中断或中断之前检测其偏差。

Cloud Insights 的查询技术和小工具信息板可用于在有组织的视图中精确定位数据中心内的问题区域。



== Cloud Insights 能否帮助我从 7- 模式迁移到 cDOT ？

可以， Cloud Insights 为现有工作负载需求和迁移后验证提供了宝贵的了解。Cloud Insights 在现代化当今数据中心方面所起的作用有助于进行变更管理模拟，迁移前优化规划以及定义合适的服务层。只需单击几下鼠标， Cloud Insights 便可轻松收集和关联多供应商环境中数千个 NFS 共享和光纤通道路径的业务影响。从迁移到技术更新， Cloud Insights 提供了一条实现可靠，规模合适的迁移的途径，并可减少计划外服务中断。



== Cloud Insights 性能监控是如何实现 " 实时 " 的？

对于内部和混合云数据中心管理， Cloud Insights 被视为近乎实时。虽然可以将轮询数据源配置为更频繁地进行，但对于大多数设备，性能收集间隔不到 5 分钟不会给大多数用户带来显著的分析优势。更频繁地收集可能会给所管理的对象和执行的分析带来不必要的负担。当然，在某些情况下，可能需要更精细的收集，幸运的是， Cloud Insights 可以提供完全的灵活性，包括可配置的设备清单和性能轮询间隔，以满足您的特定数据中心环境需求。



== 为什么我的 " 总计 " 与 " 读取 " 加上 " 写入 " 不同？

在某些情况下，您可能会注意到计数器的总数不等于该计数器的读取加写入总和。在某些情况下，可能会发生这种情况。

IOPS ：除了读取和写入之外，存储阵列或其他资产还会处理与工作负载数据流无关的内部操作。这些操作有时称为 " 系统 " ， " 元数据 " 或简单的 " 其他 " 操作，可归因于内部进程，例如快照，重复数据删除或空间重新分配。在这些情况下，要查找给定资产的系统操作量，请从总 IOPS 中减去读取和写入 IOPS 之和。" 读写 IOPS" 与数据流直接相关的总 IOPS 之和。

延迟：操作的总响应时间（延迟）有时可能报告为小于写入响应时间，因为总响应时间是时间加权平均值。I/O 工作负载通常包含的读取操作多于写入操作，而写入操作通常会观察到较长的延迟。例如，如果一个工作负载执行了 10 个读取操作，平均延迟为 5 毫秒，而执行了 5 个写入操作，平均延迟为 10 毫秒，则总加权平均延迟将通过读取次数乘以平均读取延迟计算得出。 加上写入次数乘以平均写入延迟，再除以 I/O 操作总数，例如（ 10 * 5 + 5 * 10 ） / （ 10 + 5 ） = 6.33 毫秒。
