---
sidebar: sidebar 
permalink: concept_faq.html 
keywords: FAQ, Frequently asked questions, general questions, questions 
summary:  
---
= 有关 Cloud Insights 的常见问题解答


[role="lead"]
本常见问题解答解答解答了有关 Cloud Insights 的常见问题。



== Cloud Insights 是何时推出的？

Cloud Insights 基于当今业内最成熟的基础架构监控产品，目前已有十年的积极开发。SANscreen 名称以前称为 Onaro 或 SANscreen ，加入 OnCommand 产品组合套件时发生了更改，现在称为 Cloud Insights ，更常见的是 Insight 或 Cloud Insights 。



== 在我的环境中部署 Cloud Insights 需要多长时间？

Cloud Insights 只是一个软件下载。软件安装在两个专用虚拟或物理服务器上。典型安装只需 2 小时即可完成，并且几乎会立即开始提供清单，容量和性能数据。任何其他性能和最佳实践策略，用户标注和成本感知设置都需要进行额外的规划讨论。



== Cloud Insights 是否需要代理，收集器或探针？

Cloud Insights 100% 无代理，不需要使用代理，分路器或探针。所有设备发现均为只读，带外和通过 IP 执行。



== Cloud Insights 如何发现和连接到设备？

Cloud Insights 设置可利用数据中心环境中通常已存在的原生 API 和协议，而无需代理或探针。SSH ， HTTP ， SMIS 和 CLI 只是其中的几个示例。如果已存在设备元素管理器（例如 Dell EMC 的 Unisphere ），则 Cloud Insights 会与 Element 管理器通信以捕获现有环境数据。大多数设备发现只需要 IP 地址以及只读用户名和密码。这些设备发现可以是 " 一对多 " 的，例如 Cloud Insights 的 VMware 数据收集器。通过发现 VMware vCenter ， Cloud Insights 进而可以使用一个 IP 地址和凭据发现其所有 ESXi 主机及其关联虚拟机。



== Cloud Insights 是否需要专业服务？这些功能是否可用？它们提供哪些功能？

对于规模适中的环境，我们建议使用 * 专业服务 * 进行部署，配置和集成，并提供各种自定义报告和数据验证功能。与 Cloud Insights 团队和客户接洽经理进行简短讨论有助于确定哪些服务最能让您受益。



== Cloud Insights 版本更新新功能和改进功能的频率如何？

多个版本的 Cloud Insights 均提供产品更新和服务包。主要或次要版本通常每隔几个月提供一次，服务包包括新设备支持和固件发布频率更高。这两种方法均可从 support.netapp.com 下载站点获得。某些更新会自动推送到 Cloud Insights 软件中，例如制造商经常推出的新磁盘型号。此外，在修复或更新开发之后，可以立即在站点上修补 Cloud Insights 数据收集器设备收集。



== Cloud Insights 管理团队如何确定新数据收集器请求的优先级？

Cloud Insights 的产品管理团队会主动跟踪所有客户增强功能和互操作性功能请求（ IFR ）。每个请求都经过详细评估，可行性评估，并根据客户需求和整体战略业务影响确定优先级。一旦被接受，请求将根据工作级别进行规模估算，并计划在将来进行开发。Cloud Insightss 开发流程的灵活性可以使新的数据收集器在定期计划的发布周期之外正常运行。NetApp 客户代表可以协助您处理客户咨询和代表您提交新请求。可以在站点上修补数据收集器，而无需升级 Cloud Insights 。



== 我的公司完全在 Linux 上运行。Cloud Insights 是否可以在 Linux 上运行？

可以。 Cloud Insights 支持 Red Hat Enterprise Linux 7 和 CentOS 7 ，以及采用最新 Service Pack 平台的 64 位 Windows Server 2008 R2 ， 2012 或 2012 R2 。



== Cloud Insights 是否适用于不能访问 Internet 的安全环境？

是的，目前全球排名前 10 位的财富 500 强企业以及领先的银行，医疗保健，研究和政府机构都在使用 Cloud Insights 。Cloud Insights 支持美国军用通用访问卡（ CAC ），并为地理位置分散或防火墙严重的环境提供解决方案。



== 我一直听说 OnCommand 统一管理器（ OCUM ）是 cDOT 的管理解决方案。您能否帮助我了解为什么我还会使用 Cloud Insights ？

OnCommand Unified Manager 在存储阵列的 " 设备管理 " 层运行，可对集群模式 Data ONTAP （ cDOT ）阵列及其集群互连进行深入的意外事件和基于事件的分析。Cloud Insights 提供了由 7- 模式，集群模式 Data ONTAP 和其他第三方阵列组成的内部环境和全球分布环境的整体视图。从 VM 到磁盘轴，其端到端可见性支持对容量，性能和成本建模进行历史趋势分析和预测，从而为数据中心管理提供主动式服务质量方法。



== 自动化店面中提到的 Cloud Insights 二级 ETL 是什么？

某些 Cloud Insights 自动化 StoreFront 报告下载中提及的 " 二级 ETL" 要求是指为填充到 Cloud Insights 数据仓库中的人员开发的专业服务实施，用于调用所捕获数据的额外提取，转换和加载（ ETL ）。

二级 ETL 流程的主要目的是预取 " 批量 " 数据，以便更快地生成更复杂的报告，或者按计划每天运行报告。

此二级 ETL 是对 Cloud Insights 数据仓库管理指南中详细介绍的建议的 " 每天一次 "ETL 的补充。

NetApp 专业服务有资格配置二级 ETL 脚本，以避免影响现有 Cloud Insights 报告计划，自动备份，可扩展性或其他系统性能活动。有关追加信息在 ETL 脚本编写或数据验证方面的需求，请联系您的 NetApp 销售代表，并讨论 NetApp 的专业服务如何为您提供帮助。
