---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Cloud Insights 支持 Telegraf 作为其在 Kubernetes 上收集集成数据的代理。 
---
= 在安装或升级NetApp Kubornetes监控操作员之前
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
在安装或升级之前、请阅读此信息 link:task_config_telegraf_agent_k8s.html["Kubbernetes监控操作员"]。



=== 前提条件：

|===
| 组件 | 要求 


| Kubernetes 版本 | Kubbernetes v1.20及更高版本。 


| Kubbernetes分发 | AWS El生 性Kubelnetes服务(EKS)
Azure Kubernetes Service （ AKS ）
Google Kubernetes Engine （ GKEE ）
Red Hat OpenShift
Rancher Kubernetes Engine （ RKE）
VMware Tanzu 


| Linux操作系统 | Cloud Insights不支持运行ARM64架构的节点。

网络监控：必须运行Linux内核版本4.18.0或更高版本。不支持光子操作系统。 


| 标签 | Cloud Insights 通过指定 Kubernetes 节点选择器来在这些平台上查找以下 Kubernetes 标签，支持监控运行 Linux 的 Kubernetes 节点：

Kubernetes v1.20及更高版本：Kubernetes.io/OS = Linux
作为流程编排/Kubernetes平台的是：Catcher.io/OS = Linux 


| 命令 | 必须提供URL和kubecl命令。；为获得最佳结果、请将这些命令添加到路径中。 


| 连接 | 已将kubeccli配置为与目标K8s集群通信、并可通过Internet连接到您的Cloud Insights环境。

如果您在安装期间使用代理、请按照中的说明进行操作 link:/task_config_telegraf_agent_k8s.html#configuring-proxy-support["配置代理支持"] 部分。

为了获得准确的审核和数据报告、请使用网络时间协议(NTP)或简单网络时间协议(SNTP)同步Agent计算机上的时间。 


| 其他 | 如果您运行的是OpenShift 4.6或更高版本、则除了确保满足这些前提条件之外、您还必须访问以下链接：tadd_config_testraf_agent_k8s.html#OpenShift-inInstructions [OpenShift Instructions。 


| API令牌 | 如果要重新部署Operator (即更新或替换Operator)、则无需创建新的API令牌；您可以重复使用先前的令牌。 
|===


=== 配置操作员

在较新版本的运算符中，可以在_AgentConfiguration_自定义资源中配置最常修改的设置。您可以通过编辑_operator-config.yaml文件来在部署操作员之前编辑此资源。此文件包含一些已注释掉的设置示例。请参见列表 link:telegraf_agent_k8s_config_options.html["可用设置"] 对于最新版本的运算符。

您也可以在部署操作员后使用以下命令编辑此资源：

 kubectl -n netapp-monitoring edit AgentConfiguration
要确定您部署的操作员版本是否支持AgentConfiguration、请运行以下命令：

 kubectl get crd agentconfigurations.monitoring.netapp.com
如果您看到“Error from server (NotFound)”消息，则必须先升级操作员，然后才能使用AgentConfiguration。



=== 容差和污物

netapp-CI-tentlaf-ds_、_netapp-CI-fluent-bit-ds_和_netapp-CI-net-oboder-L4-DS_ DemonSets必须在集群中的每个节点上计划一个POD、以便正确收集所有节点上的数据。操作器已配置为允许某些众所周知的*污染*。如果您在节点上配置了任何自定义污染、从而阻止Pod在每个节点上运行、则可以为这些污染创建一个*容错* link:telegraf_agent_k8s_config_options.html["在_AgentConfiguration_中"]。如果已将自定义污染应用于集群中的所有节点、则还必须向操作员部署添加必要的容错值、以便可以计划和执行操作员POD。

详细了解Kubbernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["损害和公差"]。

返回到 link:task_config_telegraf_agent_k8s.html["NetApp Kubernetes监控操作员安装*页面"]
