---
sidebar: sidebar 
permalink: security_admin_tool.html 
summary: Cloud Insights 会在整个发布生命周期遵循安全最佳实践。 
keywords: security, risk, protection 
---
= securityadmin工具
:allow-uri-read: 


[role="lead"]
CI提供了一些安全功能、可使Insight环境在增强安全性的情况下运行。这些功能包括对加密、密码哈希以及更改内部用户密码和用于对密码进行加密和解密的密钥对的功能进行了改进。

为了保护敏感数据、NetApp建议您在安装或升级后更改默认密钥和采集用户密码。

数据源加密密码存储在Cloud Insights 中、当用户在数据收集器配置页面中输入密码时、会使用公共密钥对密码进行加密。Cloud Insights 没有对数据收集器密码进行解密所需的专用密钥；只有采集单元才具有对数据收集器密码进行解密所需的数据收集器专用密钥。



== 升级和安装注意事项

如果您的Insight系统包含非默认安全配置(即您已重新设置密码密钥)、则必须备份安全配置。安装新软件或在某些情况下升级软件会将系统还原为默认安全配置。当您的系统还原到默认配置时、您必须还原非默认配置、系统才能正常运行。



== 管理采集单元上的安全性

使用SecurityAdmin工具可以管理Cloud Insights 的安全选项、该工具可在采集单元系统上运行。安全管理包括管理密钥和密码、保存和还原您创建的安全配置或将配置还原为默认设置。



== 开始之前

要执行安全配置任务、您必须对AU系统具有管理员权限。

关于此任务、可以在采集单元系统的以下任一位置找到SecurityAdmin工具：

* * Windows - C：\Program Files\SANscreen\securityadmin\bin\securityadmin.bat
* * Linux -/bin/oci-securityadmin.sh


.步骤
* *以交互模式启动SecurityAdmin工具(-I)。
+
此时将显示以下选项：

* 备份
+
为包含所有密码和密钥的存储创建一个备份zip文件、并将该文件放置在用户指定的位置或以下默认位置：

+
....
Windows - C:\Program Files\SANscreen\backup\vault
Linux - /var/log/netapp/oci/backup/vault
....
* 还原
+
还原已创建的存储的zip备份。还原后、所有密码和密钥将还原为创建备份时的现有值。

+
还原可用于同步多个服务器上的密码和密钥、例如：-更改AU上的加密密钥-创建存储备份-将存储备份还原到每个AU

* 更改加密密钥
+
更改用于对设备密码进行加密或解密的AU加密密钥。

+
更改加密密钥时、您应备份新的安全配置、以便在升级或安装后还原它。

* 更新密码
+
更改"采集"用户帐户的密码。

+
更改密码时、您应备份新的安全配置、以便在必要时还原它。

* 重置为默认值
+
将采集用户密码和采集用户加密密钥重置为默认值、默认值是在安装期间提供的值。

* 退出
+
退出SecurityAdmin工具。



选择要配置的选项、然后按照提示进行操作。
