---
sidebar: sidebar 
permalink: task_create_performance_policies.html 
keywords: performance policy, performance, thresholds, alerts, preference, delete, SVM, VM 
summary: 创建性能策略以设置阈值 
---
= 使用性能策略发出警报


[role="lead"]
您可以创建性能策略来设置阈值，这些阈值会触发警报，以向您通知与网络中资源相关的问题。例如，您可以创建一个性能策略，以便在存储池的总利用率超过 60% 时向您发出警报。

您可以为以下对象创建性能策略：

[cols="4*"]
|===


| 数据存储库 | 磁盘 | 虚拟机管理程序 | 内部卷 


| 端口 | qtree | 存储 | 存储节点 


| 存储池 | SVM | VMDK | 虚拟机 
|===


== 创建性能策略

您可以为与要监控的对象关联的指标创建具有阈值的性能策略。默认情况下，性能策略会在创建时应用于指定类型的所有对象。您可以创建标注，以便在性能策略中仅包含特定资产或一组资产。

在性能策略中使用标注时，必须在创建此策略之前存在此标注。

您可以创建一个性能策略，以便在监控的一个或多个设备超过您设置的阈值时提供通知。您的系统可能已包含满足您需求的全局策略，或者使用标注的策略在为设备添加标注时也可能起作用。

.步骤
. 在 Cloud Insights 菜单栏中，单击 * 管理 > 性能策略 *
+
此时将显示性能策略页面。策略按对象进行组织，并按其在列表中的显示顺序进行评估。

. 在性能策略页面中，单击 * + 性能策略 *
+
此时将显示 * 添加策略 * 对话框。

. 在 * 策略名称 * 字段中，输入策略的名称。
+
您必须使用对象的所有策略名称中唯一的名称。例如，不能为内部卷设置两个名为 " 延迟 " 的策略；但是，您可以为内部卷设置一个 " 延迟 " 策略，为其他卷设置另一个 " 延迟 " 策略。最佳做法是，无论对象类型如何，始终为任何策略使用唯一名称。

. 从 * 应用于类型 * 的对象列表中，选择策略适用的对象类型。
+
选择 * 虚拟机 * 。

. 从 * 带标注列表 * 中，选择一个标注类型（如果适用），然后在 * 标注值 * 框中为标注输入值，以便仅将策略应用于设置了此特定标注的对象。
. 从 * 应用窗口后 * 中选择何时发出警报以指示阈值违规。
+
首次超过阈值时 * 首次出现 * 将触发警报。所有其他选项都会在超过阈值一次且至少在指定时间内持续超过阈值时触发警报。

. 从 * 严重性 * 列表中，选择违规的严重性。
+
默认情况下，有关策略违规的电子邮件警报会发送到全局电子邮件列表中的收件人。您可以覆盖这些设置，以便将特定策略的警报发送给特定收件人。

. 在 * 创建警报 if* 部分中，选择性能计数器和运算符，然后输入一个值以创建阈值。
+
单击 * + 阈值 * 为策略添加其他计数器。

. 单击 * 保存 * 以保存新策略。
. 如果特定资产类型有多个策略，您可以更改策略的评估顺序。使用编辑菜单更改策略顺序。

