---
sidebar: sidebar 
permalink: task_kubernetes_operator_proxy.html 
keywords: telegraf, installation, install, agent, telegraf agent 
summary: 'Cloud Insights 支持 link:https://docs.influxdata.com/telegraf/v1.19/["Telegraf"] 作为收集集成数据的代理，可以在 Windows ， Linux ， macOS 和 Kubernetes 上进行配置。' 
---
= 配置代理以收集数据
:allow-uri-read: 


[role="lead"]
使用自定义 / 私有 Docker 存储库设置代理可以从 2021 年 12 月 10 日投入使用的 CI 部署开始，在 CR 中为监控操作员配置代理

kubectl -n netapp-monitoring edit agent agent-monitoring-netapp

在此文件的规范：部分中，添加以下代码块

规范：代理： isAuProxyEnabled ： <true 或 false> isTelegrafProxyEnabled ： <true 或 false> isFluentBitProxyEnabled ： <true 或 false> 密码： < 代理密码，可选 > 端口： < 代理端口 > 服务器： < 代理服务器 > 用户名： < 代理用户名，可选 > noProxy ： 使用自定义 / 专用 Docker 存储库获取 Docker 密钥。 < 应绕过代理的 IP 或可解析主机名列表以逗号分隔 >

kubectl -n netapp-monitoring get secret docker -o yaml

（复制粘贴上述命令输出中的 .dockerconfigjson ：值）将对 Docker 密钥进行解码

echo <ste粘贴 自上述步骤 1 > | base64 -d 此命令的输出格式如下： ｛ "auths" ： ｛ "docker" 。 <cluster>.cloudinsights.netapp.com" ： ｛ "username" ： "< 租户 ID>" ， "password" ： "< CI API 密钥的密码 >" ， "auth" ： "< 编码的用户名： auth 基本密码密钥。这是 Docker >" ｝ ｝ 登录到 Docker 存储库的内部组件

Docker 登录 Docker 。 <cluster>.cloudinsights.netapp.com （第 2 步） -u < 第 2 步中的用户名 > 密码： < 第 2 步中的密码 > 从 Cloud Insights 中提取操作员 Docker 映像

Docker 会拉取 Docker 。 < 集群 > .cloudinsights.netapp.com/netapp-monitoring:<version>

使用以下命令查找 <version> 字段：

kubectl -n netapp-monitoring get deployment monitoring-operator | grep "image" ：将操作员 Docker 映像推送到您的专用 / 企业 Docker 注册表

根据您的企业策略将代码推送到您的私有 / 本地 / 企业 Docker 存储库将所有开源依赖项下载到您的私有 Docker 注册表中

需要下载以下开源映像： docker.io/eraf ： 1.19.3 gcr.io/kubebuilder/Kube-RBAC 代理： v0.5.0 k8s.gcr.io/Kube-state-metrics/Kube-state-metrics ： v2.1.0

如果启用了 fluid-bit ： docker.io/fluid-bit ： 1.7.8 docker.io/Kubernetes 事件导出程序： 0.10 编辑代理 CR 以反映新的 Docker repo 位置，禁用自动升级（如果已启用）

kubectl -n netapp-monitoring edit agent agent-monitoring-netapp

enableAutoUpgrade ： false docker-repo ： <Docker repo of the enterprise/corp docker repo> dockerRepoSecret ： <optional ： name of the Docker secret of enterprise/corp docker repo ， this secret should be already created on the K8s cluster in the same namespacy>

在规范：部分中，进行以下更改：

规格： Telegraf ： - 名称： KSM 替换项： - 密钥： K8s.GCR.IO 值： < 与上面的 "docker-repo" 字段相同 >
