---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: 配置 NetApp StorageGRID 数据收集器 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID 数据收集器
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp StorageGRID 数据收集器支持从 StorageGRID 配置收集清单和性能。


NOTE: StorageGRID 按不同的原始 TB 到受管单元速率进行计量。每 40 TB 未格式化的 StorageGRID 容量计费为 1 link:concept_subscribing_to_cloud_insights.html#pricing["受管单元（ MU ）"]。



== 术语

数据基础架构洞察从NetApp StorageGRID收集器采集以下清单信息。对于所采集的每种资产类型，均显示了此资产最常用的术语。查看此数据收集器或对其进行故障排除时，请记住以下术语：

[cols="2*"]
|===
| 供应商 / 型号术语 | 数据基础架构洞察力一词 


| StorageGRID | 存储 


| 节点 | 节点 


| 租户 | 存储池 


| 存储分段 | 内部卷 
|===


== 要求

以下是配置此数据源的要求：

* StorageGRID 主机 IP 地址
* 分配了 Metric 查询和租户访问角色的用户的用户名和密码
* 端口 443




== 配置

[cols="2*"]
|===
| 字段 | 说明 


| StorageGRID 主机 IP 地址 | StorageGRID 设备的管理虚拟 IP 地址 


| 用户名 | 用于登录到 StorageGRID 设备的名称 


| 密码 | 用于登录到 StorageGRID 设备的密码 
|===


== 高级配置

[cols="2*"]
|===
| 字段 | 说明 


| 清单轮询间隔（分钟） | 默认值为 60 分钟 


| 性能轮询间隔（秒） | 默认值为 900 秒 
|===


== 单点登录（ SSO ）

。 link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"] 固件版本具有相应的 API 版本； 3.0 API 及更高版本支持单点登录（ Single Sign-On ， SSO ）登录。

|===


| 固件版本 | API 版本 | 支持单点登录（ SSO ） 


| 11.1 | 2. | 否 


| 11.2. | 3.0 | 是的。 


| 11.5 | 3.3 | 是的。 
|===


== 故障排除

可从中找到此数据收集器上的追加信息 link:concept_requesting_support.html["支持"] 页面或中的 link:reference_data_collector_support_matrix.html["数据收集器支持列表"]。
