---
sidebar: sidebar 
permalink: task_troubleshooting_general_problems.html 
summary: 常规 Cloud Insights 故障排除提示。 
keywords: troubleshooting, problems, browser, login, log in, accessing, access to, Trident, qtree, quota 
---
= 对常规 Cloud Insights 问题进行故障排除
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以在此处找到有关 Cloud Insights 故障排除的建议。

另请参见 link:task_troubleshooting_linux_acquisition_unit_problems.html["排除 Linux 采集单元问题"] 和 link:task_troubleshooting_windows_acquisition_unit_problems.html["对 Windows 采集单元问题进行故障排除"]。



== 登录问题

|===
| * 问题： * | * 请尝试此操作： * 


| Cloud Insights 每 5 分钟注销一次 | 396149d67edd166e53b49c38f4b707ba 


| e4ff2e59dd571d2bbd5a906b6fad2546 | a9a216fbb1fb9d774e7cedfcf74c00cf 


| 我受邀访问 Cloud Insights ，但收到 " 未授权 " 消息。 | 199017f1d912993f091b6b969d3442ad 


| 176f8c6fa466059df49f2717c021d306 | 7a8624fb56224e907698f45ef2e4cc47 


| 几天后，我被自动注销。 | ed6e79e2f9b9c201ed834c6efeb7f356 


| 我收到错误消息 " 不再授权登录 " 。 | acf29dcaa06698c29122cba5402e3145 


| 其他登录错误 | 请尝试在 Chrome 中使用匿名模式，或者清除浏览器历史记录， Cookie 和缓存。请尝试使用其他浏览器配置文件（例如 Chrome - 添加人员）。 
|===


== 其他问题

|===


| *问题:* | *问题解答 ：* 


| 我的qtree硬配额在查询中显示正确、但软配额显示为卷的总容量。是否正确？ | 只有硬配额(无论是手动设置还是通过三叉设计来设置)才会显示为设置的配额；如果未指定硬配额、则qtree容量将是内部卷容量。 


| 我在同一个qtree中同时手动设置了软配额和硬配额、但显示的总容量是硬配额；是否正确？ | 是、如果指定了硬配额、则显示为总容量。 


| 在输入Cognos报告计划时间时、有时会在计划时间中额外增加"m"。例如、如果我输入时间为"02：15 PM"、则可能会添加一个额外的字符："02：15 PMM"(或PMM)。当我单击"外部"时、它将更改为"凌晨2：15 "。

我可以保存报告、但当我重新打开已保存的报告时、计划时间显示为AM (即上午)、无论我在计划时间中输入的是AM还是PM。 | 重新输入计划时间、注意不要输入完整的"AM"或"PM"字符；只需键入"A"表示"AM"或"P"表示"PM"即可。如果未显示多余字符、则计划时间将正确设置。 
|===


== 资源

有关其他故障排除提示，请参见 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights["NetApp 知识库"] （需要支持部门登录）。

有关其他支持信息，请参见 Cloud Insights link:concept_requesting_support.html["支持"] 页面。

如果您拥有有效的 Cloud Insights 订阅，则可以使用以下支持选项：

link:https://www.netapp.com/us/contact-us/support.aspx["电话"]
link:https://mysupport.netapp.com/site/cases/mine/create?serialNumber=95001014387268156333["支持服务单"]

有关详细信息，请参见 https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html["Cloud Insights 支持文档"]。
