---
sidebar: sidebar 
permalink: task_h2_minrisk_thin.html 
keywords: thin provisioning, how to, policy 
summary: 最大限度地减少精简配置中的随机。 
---
= 最小化精简配置风险简介


[role="lead"]
在当今的混合 IT 数据中心中，管理员面临着通过采用精简配置等容量效率技术来控制分配和利用以前不可用的容量来将资源利用率延伸到物理范围以外的压力。

Cloud Insights 可提供 IT 服务堆栈中多个精简配置层以往近乎实时的容量使用情况和利用率详细信息。如果未能正确管理超额预订风险，可能会导致业务停机时间不及时。



== 监控存储池

每个存储池登录页面都提供超额预订比率，确定相关资源， LUN 和磁盘利用率，以及存储池发生的策略违规和违规。

使用存储池登录页面确定支持虚拟基础架构的物理资产存在的任何潜在问题。您可以跟踪 30 天内的容量和容量比率趋势，也可以使用自定义时间范围。请注意以下各节中的数据以监控存储池的状态。

使用 * 摘要 * 部分了解：

* 存储池容量信息，包括物理容量和过量使用的容量。
* 聚合是否超额预订以及超额预订的数量
* 发生的任何策略违规
* 使用 * 存储资源 * 部分了解 LUN 利用率
* 使用 * 磁盘 * 部分了解构成存储池的各个磁盘
* 使用 * 资源 * 部分了解 VMDK 与 LUN 的关联，并了解存储与 VM 的应用程序路径
* 使用 * 违规 * 部分可确定是否违反为存储池设置的性能策略。




== 监控数据存储库

数据存储库登录页面可确定超额预订比率， LUN 和磁盘利用率，相关资源，并显示数据存储库发生的策略漏洞和违规。

使用此登录页面确定虚拟基础架构的问题。您可以跟踪容量和容量比率趋势以预测容量变化。

使用 * 摘要 * 部分了解：

* 数据存储库容量信息，包括物理容量和过量使用的容量。
* 过量使用容量的百分比。
* 延迟， IOPS 和吞吐量指标。


"* VMDKs* " 部分显示了虚拟磁盘容量和性能。"* 存储资源 * " 部分显示与数据存储库相关的内部卷的已用容量和性能指标。使用 * 资源 * 部分了解 VMDK 与 LUN 的关联，并了解存储与 VM 的应用程序路径。



== 创建信息板以监控精简配置环境

通过提供灵活的信息板小工具设计和显示图表选项，可以深入分析容量使用情况和利用率，并提供战略信息，最大限度地降低精简配置的数据中心基础架构中的风险。

您可以创建信息板来访问要监控的数据存储库和存储池信息。



=== 使用信息板访问数据存储库信息

您可能需要创建信息板，以便快速访问要在虚拟基础架构中监控的数据。信息板可能包含类似于以下内容的小工具，用于根据过量使用的 % 确定排名前 10 位的数据存储库，并可包含一个小工具，用于显示数据存储库的容量数据。信息板使用变量突出显示过量使用超过 150% 的数据存储库和超过 80% 已用容量的数据存储库。

图像： top_10_overcommit.png



== 使用性能策略降低精简配置的风险

您应创建性能策略，以便在违反虚拟基础架构中的阈值时发出警报。通过这些警报，您可以在环境发生发生原因操作中断或中断之前对环境中的更改做出响应。

有助于监控虚拟基础架构的策略包括：

* 数据存储库 * 您可以创建密切监控数据存储库容量的策略：

* 容量比率—过量使用
* 容量比率—已用
* Capacity —已用
* 容量—总计


* 存储池 * 您可以创建策略，防止在精简配置环境中发生存储池容量中断：

* 已配置容量
* 已用容量
* 容量比率—过量使用
* 容量比率—已用


您可以通过为这些资产创建其他策略来从这些策略进行扩展，以监控虚拟基础架构中的容量：

* 内部卷
* LUN
* 磁盘
* VMDK
* 虚拟机


您可以使用标注配置策略。您可以为支持应用程序的特定资产分配相同的标注。例如，您可以为精简配置应用程序的数据存储库和存储池分配标注。

您可能有名为生产环境的标注，开发环境的标注等。您可以根据资产支持的应用程序类型更改警告的阈值和严重性。

例如，违反生产应用程序数据存储库的阈值可能会引发严重警告，而对于开发环境，同样的违规可能只会引发警告。

将标注集成到定义的策略中可以减少非关键资产的不必要警报噪声。



== 为存储池创建性能策略

您可以创建性能策略，以便在超过存储池资产阈值时触发警报以向您发出通知。

* 开始之前


此操作步骤假定您已对存储池进行精简配置。

* 关于此任务


您希望创建策略来监控和报告存储池中可能导致中断的更改。对于精简配置的物理存储池，您希望监控物理容量并监控过量使用比率。

* 步骤
+
.. 在 Cloud Insights 菜单中，单击 * 管理 > 性能策略 *
+
此时将显示性能策略页面。策略按对象进行组织，并按其在列表中的显示顺序进行评估。启用通知（ * 管理员 > 通知 * ）后，您可以将 Insight 配置为在违反性能策略时发送电子邮件。

.. 单击 * + 性能策略 * 以创建新策略
.. 在 * 策略名称 * 中，输入策略的唯一名称
.. 在 * 应用于类型 * 的对象中，选择存储池
.. 在 * 应用后窗口 * 中，输入首次出现。
.. 在 * 严重性 * 中输入严重
.. 配置要在违反阈值时收到通知的电子邮件收件人。
+
默认情况下，有关策略违规的电子邮件警报会发送到全局电子邮件列表中的收件人。您可以覆盖这些设置，以便将特定策略的警报发送给特定收件人。

+
单击链接以打开收件人列表，然后单击 + 按钮以添加收件人。此策略的违规警报将发送到列表中的所有收件人。

.. 在 * 如果以下任一项为 true ，则创建警报 * 中，输入 Capacity ratio - used > 85%


* 结果


此配置会导致系统在存储池的物理容量超过 85% 时发送严重警告消息。使用 100% 的物理内存将导致应用程序失败。



== 为数据存储库创建性能策略

您可以为与要监控的存储池相关的数据存储关联的指标创建性能策略，并设置阈值。

默认情况下，性能策略会在创建时应用于指定类型的所有设备。您可以创建一个标注，以便在性能策略中仅包含一个特定设备或一组设备。

. 开始之前


在性能策略中使用标注时，必须在创建此策略之前存在此标注。

您可以创建一个性能策略，以便在监控的一个或多个数据存储库超过您设置的阈值时提供通知。您的系统可能已包含满足您需求的全局策略。通过使用标注的策略，您可以更加关注特定数据存储库。

.步骤
. 在 Cloud Insights 工具栏中，单击 * 管理 > 性能策略 *
. 单击 * + 性能策略 *
. 添加 " 策略名称 "
+
您必须使用与对象的所有其他策略名称不同的名称。例如，不能为内部卷设置两个名为 " 延迟 " 的策略；但是，您可以为内部卷设置一个 " 延迟 " 策略，为数据存储库设置另一个 " 延迟 " 策略。最佳做法是，无论对象类型如何，始终为任何策略使用唯一名称。

. 选择 " 数据存储库 " 作为对象类型
. 单击 " 首次出现 "
. 在 * 策略名称 * 中，输入策略的唯一名称
. 在 * 应用于类型 * 的对象中，选择数据存储库
. 在 * 带标注 * 中，选择标注的名称
. 在 * 标注值 * 中，选择所需的值
. 在 * 应用后窗口 * 中，输入首次出现
. 在 * 严重性 * 中输入严重
. 配置电子邮件收件人
. 在 * 创建警报 * 中，输入 Capacity ratio - over commit > 150
. 单击 * + Threshold* 以添加其他阈值，例如总容量和已用容量。

